services:
  node-backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: node dist/index.js
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - shared-networks

  celery-worker:
    build:
      context: ./server1
      dockerfile: Dockerfile
    env_file:
      - ./server1/.env
    networks:
      - shared-networks

networks:
  shared-networks:
    external: true
