import dotenv from "dotenv";

dotenv.config();

const PORT = process.env.PORT || 3000;

const POSTGRES_DATABASE_HOST = process.env.POSTGRES_DATABASE_HOST;
const POSTGRES_DATABASE_NAME = process.env.POSTGRES_DATABASE_NAME;
const POSTGRES_DATABASE_USER = process.env.POSTGRES_DATABASE_USER;
const POSTGRES_DATABASE_PASSWORD = process.env.POSTGRES_DATABASE_PASSWORD;
const POSTGRES_DATABASE_PORT = Number(process.env.POSTGRES_DATABASE_PORT);

const DB_URL = process.env.DB_URL!;
const FRONTEND_URL = process.env.FRONTEND_URL!;

const REDIS_USERNAME = process.env.REDIS_USERNAME;
const REDIS_PASSWORD = process.env.REDIS_PASSWORD;
const REDIS_HOST = process.env.REDIS_HOST;
const REDIS_PORT = Number(process.env.REDIS_PORT);
const CELERY_BROKER_URL = process.env.CELERY_BROKER_URL;
const CELERY_BACKEND = process.env.CELERY_BACKEND;

export {
  CELERY_BACKEND,
  CELERY_BROKER_URL,
  DB_URL,
  FRONTEND_URL,
  PORT,
  POSTGRES_DATABASE_HOST,
  POSTGRES_DATABASE_NAME,
  POSTGRES_DATABASE_PASSWORD,
  POSTGRES_DATABASE_PORT,
  POSTGRES_DATABASE_USER,
  REDIS_HOST,
  REDIS_PASSWORD,
  REDIS_PORT,
  REDIS_USERNAME,
};
