import dotenv from "dotenv";

dotenv.config();

const PORT = process.env.PORT || 3000;

const DB_URL = process.env.DB_URL!;
const FRONTEND_URL = process.env.FRONTEND_URL!;

const REDIS_USERNAME = process.env.REDIS_USERNAME;
const REDIS_PASSWORD = process.env.REDIS_PASSWORD;
const REDIS_HOST = process.env.REDIS_HOST;
const REDIS_PORT = Number(process.env.REDIS_PORT);
const CELERY_BROKER_URL = process.env.CELERY_BROKER_URL;
const CELERY_BACKEND = process.env.CELERY_BACKEND;

const CELERY_TASK_CLASSIFY = process.env.CELERY_TASK_CLASSIFY;
const CELERY_TASK_PROBABILITY = process.env.CELERY_TASK_PROBABILITY;
const CELERY_TASK_CLASSIFY_NAIVE_BAYES =
  process.env.CELERY_TASK_CLASSIFY_NAIVE_BAYES;

export {
  CELERY_BACKEND,
  CELERY_BROKER_URL,
  DB_URL,
  FRONTEND_URL,
  PORT,
  REDIS_HOST,
  REDIS_PASSWORD,
  REDIS_PORT,
  REDIS_USERNAME,
  CELERY_TASK_CLASSIFY,
  CELERY_TASK_PROBABILITY,
  CELERY_TASK_CLASSIFY_NAIVE_BAYES,
};
